import 'package:ruserapp/model/results.dart';
import 'package:ruserapp/networking/api_client_provider.dart';

class FetchRandomUserListRepository {
  ApiProvider _provider = new ApiProvider();

  /*this method was called in the UserListBloc*/
  Future<Autogenerated> fetchUserList() async {
    final response = await _provider.get('/?results=10');
    return Autogenerated.fromJson(response);
  }
}
