import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:ruserapp/model/results.dart';
import 'package:ruserapp/networking/api_client_provider.dart';

class FetchRandomUserListRepository {
  ApiProvider _provider = new ApiProvider();

  /*this method was called in the UserListBloc*/
  Future<Autogenerated> fetchUserList() async {
    var url = Uri.parse('https://randomuser.me/api/?results=10');
    final response = await http.get(url);
    debugPrint('RESPONSE: $response');
    return null;
  }
}
